version: '3'
services:
  app:
    profiles: ['devcontainer']
    container_name: royals-dev
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    stdin_open: true
    tty: true
    command: sleep infinity
    environment:
      DEVCONTAINER: 1

  dev-db:
    container_name: royals-dev-db
    image: postgres:14-alpine
    ports:
      - 5443:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: royals

  dev-cache:
    container_name: royals-dev-cache
    image: redis:7-alpine
    ports:
      - 6390:6379
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "1234"
