name: CD_BACK

on:
  workflow_run:
    workflows: [CI_BACK]
    types: [completed]
    branches: [main]

jobs:
  deploy-to-s3:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_AND_CODE_DEPLOY_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_AND_CODE_DEPLOY_SECRET }}
          aws-region: ap-northeast-2

      - name: Copy deploy script
        run: cp scripts/deploy.sh backend/deploy.sh

      - name: Copy appspec.yml
        run: cp appspec.yml backend/appspec.yml

      - name: Copy env file from S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            s3://royals-api-server-env/.env backend/.env

      - name: zip file
        run: tar -zcvf target.tar.gz backend

      - name: Deploy backend dir to S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            target.tar.gz s3://royals-api-server/nest/target.tar.gz

      - name: code-deploy
        run: |
          aws deploy create-deployment \
          --application-name royals_api_deploy \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name api_server_auto_scaling \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=royals-api-server,bundleType=tgz,key=nest/target.tar.gz \
          --region ap-northeast-2 \
