name: CD_BACK

on:
  workflow_run:
    workflows: [CI_BACK]
    types: [completed]
    branches: [main]

jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - uses: actions/checkout@v3
      - name: Run scripts in main_server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            . ~/.nvm/nvm.sh
            nvm use 19
            npm install -g pnpm
            cd nest/royals-staff
            git reset --hard
            git fetch
            git pull
            pnpm install
            pnpm install -g dotenv-cli
            pnpm --filter backend exec migrate:prod
            pnpm --filter backend exec prisma generate
            pnpm --filter backend build
            pnpm --filter backend start:reload

      - name: Run scripts in sub_server_1
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST_2 }}
          username: ${{ secrets.USER }}
          script: |
            . ~/.nvm/nvm.sh
            nvm use 19
            npm install -g pnpm
            cd nest/royals-staff
            git reset --hard
            git fetch
            git pull
            pnpm install
            pnpm --filter backend exec prisma generate
            pnpm --filter backend build
            pnpm --filter backend start:reload

      - name: Run scripts in sub_server_2
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST_3 }}
          username: ${{ secrets.USER }}
          script: |
            . ~/.nvm/nvm.sh
            nvm use 19
            npm install -g pnpm
            cd nest/royals-staff
            git reset --hard
            git fetch
            git pull
            pnpm install
            pnpm --filter backend exec prisma generate
            pnpm --filter backend build
            pnpm --filter backend start:reload

      - name: Remove Github Actions IP From Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
