name: CD_FRONT_STAFF

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/staff/**'

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter "frontend/staff" install

      - name: Lint
        run: pnpm lint:staff

      - name: Check style
        run: pnpm format:check:staff

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter "frontend/staff" install

      - name: Check types in Typescript
        run: pnpm --filter "frontend/staff" type-check

  deploy-to-s3:
    needs: [lint, test]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter "frontend/staff" install

      - name: Build
        run: pnpm --filter "frontend/staff" build

      - name: Cache dist
        uses: actions/cache@v3
        with:
          path: ./*/dist
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-${{ github.sha }}-staff

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_S3_SECRET_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            frontend/staff/dist s3://staff.skku-royals.football
