name: CI_BACK

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [19]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter backend install

      - name: Generate Prisma Client
        run: pnpm --filter backend exec prisma generate

      - name: Build
        run: pnpm --filter backend build

      - name: Cache dist
        uses: actions/cache@v3
        with:
          path: backend/dist
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-${{ github.sha }}

      - name: Copy script
        run: cp scripts/deploy.sh backend/deploy.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_AND_CODE_DEPLOY_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_AND_CODE_DEPLOY_SECRET }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            backend s3://royals-api-server

  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [19]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter backend install

      - name: Lint
        run: pnpm --filter backend lint

      - name: Check style
        run: pnpm --filter backend format:check

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [19]

    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: royals

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter backend install

      - name: Generate Prisma Client
        run: pnpm --filter backend exec prisma generate

      - name: Check Prisma Migration
        env:
          DATABASE_URL: postgresql://postgres:1234@127.0.0.1:5432/royals?schema=public
        run: |
          pnpm --filter backend exec prisma migrate diff \
            --from-migrations ./prisma/migrations \
            --to-schema-datamodel ./prisma/schema.prisma \
            --shadow-database-url postgresql://postgres:1234@127.0.0.1:5432/royals?schema=public \
            --exit-code

      - name: Check types in Typescript
        run: pnpm --filter backend exec tsc --noEmit

      - name: Test
        run: pnpm --filter backend test
